spring:
  application:
    name: drone
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  h2:
   console:
    enabled: true
    path: /h2-console

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG