CREATE TABLE DRONE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SERIAL_NUMBER VARCHAR(100) UNIQUE NOT NULL,
    MODEL VARCHAR(50) NOT NULL,
    WEIGHT_LIMIT INT NOT NULL,
    BATTERY_CAPACITY INT NOT NULL,
    STATE VARCHAR(50) NOT NULL
);

CREATE TABLE PAYLOAD_BASE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    WEIGHT INT NOT NULL,
    DRONE_ID BIGINT,
    PAYLOAD_TYPE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE(ID)
);

CREATE TABLE MEDICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(255),
    CONSTRAINT FK_MEDICATION_PAYLOAD FOREIGN KEY (ID) REFERENCES PAYLOAD_BASE(ID)
);


CREATE TABLE BATTERY_AUDIT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DRONE_ID BIGINT NOT NULL,
    BATTERY_LEVEL INT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL,
    CONSTRAINT FK_BATTERY_AUDIT_DRONE FOREIGN KEY (DRONE_ID) REFERENCES DRONE(ID)
);